language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r test-requirements.txt"
  - "pip install . --use-mirrors"

script: django-admin.py test --settings wbinventory.tests.testproject.settings -v2 wbinventory
